node{
  stage('SCM Checkout'){
    git 'https://github.com/Jhmedinaa/GestionConfiguracion'  
  }
  stage('Compile-Package'){
    def mvnHome = tool name: 'maven', type: 'maven'
    sh "'${mvnHome}/bin/mvn' spring-boot:run"
  }
}
